### ISSUE TITLE
radcli does not failover to backup server

### ISSUE THREAD

**Issue by mcr** [radcli/radcli#1]
Having converted my PPPoE BMS/LNS, from my hacked radiusclient to radcli, I find that it does no better than the old library when it comes to failing over from one server to another.
It did pretty much work out of the box with all of the IPv6 attributes.
WELL, NO. I mis-tested... was old code.

I'm opening this issue not to complain, but rather to indicate that work on fixing this has started.

**Comment by nmav** [comment]
You are right. On last release I removed that feature in order to simplify the code, on the grounds it is not a feature often used (was not documented at least). If it is a widely used feature it would make sense to bring that back.

**Comment by nmav** [comment]
I'd have expected that server fallback is something the server should concern itself (e.g., the same way haproxy works for http), rather than the client.

**Comment by nmav** [comment]
@mcr do you think that server fallback should be handled by radcli itself? As I see re-adding that behaviour affects thread-safety as well. I'd prefer to keep things simple unless that's the only choice.

**Comment by mcr** [comment]
I have been humming and hawing a lot about this, as I look at the structure, and try to decide.
I think that a sensible system would use a localhost freeradius instance as a proxy, but not all systems are big enough to accommodate that.  So, I think that it will be a layer above radcli; I also need for it to keep some stats across processes so that every one of my 10000 pppd processes doesn't try the "dead" radius server first.  I'm thinking about a /dev/shm segment; I also thought about a helper process that would fork() from the main and remain running, or something that would be started.  While you can setup some servers to manage a virtual IP, radius servers are often distributed across many layer-2 segments, with the idea that each machine talks to the local server first, and the remote one if it has to.

**Comment by nmav** [comment]
I'm leaning into bringing this functionality back. I see that there is no real support for something like a haproxy in radius, and existing software relies on the client being able to fallback. Unless you have some objection I'll bring that functionality back.

**Comment by mcr** [comment]
@nmav, I have code, I haven't pushed it yet.  There is at present no support for the memory that I described above.

**Comment by nmav** [comment]
This has already been resolved.
