### ISSUE TITLE
max length of radius secret in radcli

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [radcli/radcli#103]
See [openconnect/recipes !28](https://gitlab.com/openconnect/recipes/-/merge_requests/28):
> [...] discovered radius authentication is not working because authentik-radius outpos has shared secret 128 characters in length while radcli silently limits length to be less than 96 characters.

This appears to be the source of this limitation:
https://github.com/radcli/radcli/blob/153452b531722e57e6c83dd03c70e76482852942/include/radcli/radcli.h#L56

Would it make sense to increase it to 8 * 16?

**Comment by nmav** [comment]
The question would be why the existing limit is not enough? There always be some use for an extremely large number of characters, but the default values do not necessarily need to cope for that. To change the default the best would be to understand the reason to do so.

**Comment by DimitriPapadopoulos** [comment]
The "reason" is:
> authentik-radius outpos has shared secret 128 characters in length

The max length is probably buried somewhere in https://github.com/goauthentik/authentik/tree/main/authentik/providers/radius or even higher up under https://github.com/goauthentik/authentik/tree/main.

**Comment by nmav** [comment]
So it generates a 128-character secret by default or it has a max length of 128-characters?

**Comment by DimitriPapadopoulos** [comment]
It's hard to infer from the source code. I'll ask the end-user...

**Comment by DimitriPapadopoulos** [comment]
When authenticating using `radtest` from freeradius, with _1234_ as the password, the authentik radius server sends this JSON message internally:
```
[Path with value: /password:1234]
[Member with value: password:1234]
String value: 1234
Key: password
[Path: /password]
```
When authenticating using `radtest` from ocserv, again with _1234_ as the password, the authentik radius server sends that JSON message:
```
[Path with value: /password:YS\ufffd\ufffd\u0007ag\ufffdag\ufffdiS\ufffd\ufffd\ufffd\ufffd\u001e\ufffd]
[Member with value: password:YS\ufffd\ufffd\u0007ag\ufffdag\ufffdiS\ufffd\ufffd\ufffd\ufffd\u001e\ufffd]
String value: YS\ufffd\ufffd\u0007ag\ufffdag\ufffdiS\ufffd\ufffd\ufffd\ufffd\u001e\ufffd
Key: password
[Path: /password]
```
Do you have an clue where this difference come from? Could ocserv be hashing the _1234_ password to something starting with `YS`?

**Comment by corpix** [comment]
@DimitriPapadopoulos I am not an expert in authentik, but it looks like secret is generated during radius outpost setup [in authentik web interface
](https://github.com/goauthentik/authentik/blob/b5928c2f7fff0fbe4470f28da584625bd5ac065f/web/src/admin/applications/wizard/methods/radius/ak-application-wizard-authentication-by-radius.ts#L62)

Not sure why it is 128, I've read the `User-Password` section of the [RFC2865](https://datatracker.ietf.org/doc/html/rfc2865#section-5.2), it is not very clear for me, but I don't think there is an upper limit on the password length.
I have also gave a quick grep on freeradius sources and haven't found any limits for password length.

I think it may be a good idea to ask @kensternberg-authentik or @BeryJu (they have touched the authentik radius wizard code corresponding to git blame :slightly_smiling_face: ) why 128 was chosen.

**Comment by DimitriPapadopoulos** [comment]
Thank you so much for the links. They are not crystal clear to me either, but [RFC2865](https://datatracker.ietf.org/doc/html/rfc2865#section-5.2) does say:
> The String field is between 16 and 128 octets long, inclusive.

**Comment by BeryJu** [comment]
I honestly don't remember why the default secret length was set to 128, but it has been that value from the start: https://github.com/goauthentik/authentik/commit/3f5effb1bcae8cbb46b39d17292b3a2b3a8fea73

**Comment by DimitriPapadopoulos** [comment]
However, I am not an expert of Radius, and still fail to understand how the following relate and interact:
* `User-Password` which is between 16 and 128 octets long,
* the shared secret,
* https://github.com/radcli/radcli/blob/153452b531722e57e6c83dd03c70e76482852942/include/radcli/radcli.h#L49
* https://github.com/radcli/radcli/blob/153452b531722e57e6c83dd03c70e76482852942/include/radcli/radcli.h#L56

**Comment by DimitriPapadopoulos** [comment]
The shared secret should be at least 16 octets:
> The secret (password shared between the client and the RADIUS server) SHOULD be at least as large and unguessable as a well-chosen password.  It is preferred that the secret be at least 16 octets.

A [Google search](https://www.google.com/search?q=max+mength+of+radius+shared+secret) came up with empirical information on upper limits:
* _[Please enlarge the maximum Shared secret lengt in RADIUS Authenticattion Server settings](https://community.ui.com/questions/Please-enlarge-the-maximum-Shared-secret-lengt-in-RADIUS-Authenticattion-Server-settings/06bcf334-2cfe-4985-8cb4-dfc8433c42ae)_
  > Microsoft RADIUS server does go up to 128 chars.
* [Technical Tip: The maximum radius secret key length for FortiOS](https://community.fortinet.com/t5/FortiGate/Technical-Tip-The-maximum-radius-secret-key-length-for-FortiOS/ta-p/200042)_
  > In conclusion, the maximum length of Radius Secret key on the FortiOS is 128 characters.
* _[`/etc/radius/clients` file](https://www.ibm.com/docs/en/aix/7.3?topic=files-etcradiusclients-file)_ from the [AIX documentation](https://www.ibm.com/docs/en/aix/7.3)
  > The maximum length of the shared secret is 256 bytes and is case sensitive.
* _[Best Practices for Implementing a Radius Server​](https://cloudinfrastructureservices.co.uk/best-practices-for-implementing-a-radius-server/)_
  > If you are looking for maximum security, make your shared secret up to 128 characters long.
* _[Configuring a RADIUS Server](https://www.arubanetworks.com/techdocs/ArubaOS_8.12.0_Web_Help/Content/arubaos-solutions/auth-servers/conf-radi-serv.htm#aaa_servers_3503549366_1037376)_ from the [ArubaOS documentation](https://www.arubanetworks.com/techdocs/ArubaOS_8.12.0_Web_Help/Content/home.htm):
  > Shared secret between the controller and the authentication server. The maximum length is 128 characters.
* _[Configuring RADIUS Servers](https://sc1.checkpoint.com/documents/R81/WebAdminGuides/EN/CP_R81_Gaia_AdminGuide/Topics-GAG/RADIUS-Servers.htm)_ from Check Point's [Gaia R81 Administration Guide](https://sc1.checkpoint.com/documents/R81/WebAdminGuides/EN/CP_R81_Gaia_AdminGuide/Topics-GAG/Gaia-Overview.htm)
  > Enter the shared secret text string up to 256 characters, without any whitespace characters and without a backslash.
  
  > Some RADIUS servers have a maximum string length for shared secret of 15 or 16 characters.
* _[RadiusSettings](https://docs.aws.amazon.com/directoryservice/latest/devguide/API_RadiusSettings.html)_ from the [AWS Directory Service Documentation](https://docs.aws.amazon.com/directory-service/)
  > Length Constraints: Minimum length of 8. Maximum length of 512.
* _[Client Definitions](https://freeradius.org/documentation/freeradius-server/4.0.0/raddb/clients.conf.html)_ from [The FreeRADIUS Server](https://freeradius.org/documentation/freeradius-server/4.0.0/index.html) documentation
  > The secret can be any string, up to 8k characters in length.
  
  However, the client source code begs to differ as far as I can understand:
  
  [**include/freeradius-client.h**](https://github.com/FreeRADIUS/freeradius-client/blob/5a7c7766eaf055e022b339cd4dc9c49720425087/include/freeradius-client.h#L61)<br/>Line 61 in [5a7c776](https://github.com/FreeRADIUS/freeradius-client/commit/5a7c7766eaf055e022b339cd4dc9c49720425087)
  ```c
  #define MAX_SECRET_LENGTH	(16 * 16) /* MUST be multiple of 16 */
   ```

A maximal length of 256 would cover a majority of commercial RADIUS servers, would be compatible with FreeRADIUS, and should cover most use cases in practice.

**Comment by nmav** [comment]
The shared secret is the secret between ocserv and radius server.

**Comment by DimitriPapadopoulos** [comment]
Yes, it took me some time, but I eventually sorted it out :smile:
