### ISSUE TITLE
Missing Message-Authenticator attribute by default

### ISSUE THREAD

**Issue by apla** [radcli/radcli#106]
I've configured `OpenConnect` server to use `RADIUS` auth and `Message-Authenticator` attribute not sent.

`OpenConnect` is using `radcli` for authentication and I'm not sure it is an issue for a `OpenConnect` or `radcli`.

Why it is important? RADIUS is vulnerable for a [MD5 collision attack called Blast-RADIUS](https://blog.cloudflare.com/radius-udp-vulnerable-md5-attack)

Maybe it is a good idea to configure radcli to calculate and send `Message-Authenticator` attribute by default?

**Comment by nmav** [comment]
radcli supports DTLS and TLS for securing radius use that. MD5 and radius are broken since early 2000's.

**Comment by pem** [comment]
See another issue reported (still open) regarding this (#107).

It's unfortunately not that simple. We have customers where the client side people don't control the server side. They don't get to choose TLS, and they just get the order, "use Message-Authenticator from now on". So we need to include it, even if it's broken and stupid.

**Comment by nmav** [comment]
If that's important to you I suggest you create a pull request.
