### ISSUE TITLE
LITTLE_ENDIAN and BIG_ENDIAN redefined

### ISSUE THREAD

**Issue by mcr** [radcli/radcli#2]
In compilation I get the following warning.  I can't find LITTLE_ENDIAN or BIG_ENDIAN used in the code anywhere, so I propose that we remove this from configure.ac completely.

    libtool: compile:  gcc -DHAVE_CONFIG_H -DRC_LOG_FACILITY=LOG_DAEMON -I. -I.. -I. -I../include -I.. -Wall -g -O2 -MT sendserver.lo -MD -MP -MF .deps/sendserver.Tpo -c sendserver.c  -fPIC -DPIC -o .libs/sendserver.o
    In file included from md5.h:11:0,
                 from rc-md5.h:20,
                 from sendserver.c:20:
    ../config.h:185:0: warning: "LITTLE_ENDIAN" redefined
     #define LITTLE_ENDIAN 1
     ^
     In file included from /usr/include/i386-linux-gnu/sys/types.h:216:0,
                 from ../include/includes.h:20,
                 from sendserver.c:15:
    /usr/include/endian.h:45:0: note: this is the location of the previous definition
     # define LITTLE_ENDIAN __LITTLE_ENDIAN
    ^

**Comment by nmav** [comment]
I've removed these definitions completely. They weren't used.
