### ISSUE TITLE
Using radcli without a dictionary, or make it easier to find a dictionary

### ISSUE THREAD

**Issue by zorun** [radcli/radcli#24]
When using radcli in a program, it's annoying to have to load the dictionary from a file.  In particular:

- it is difficult to know the location of the dictionary in advance, especially for portable code (various Linux distro, OS X, FreeBSD...).  For instance Debian uses `/etc/radcli/dictionary` but Arch uses `/usr/share/radcli/dictionary`. For local installs the dictionary could also be in `/usr/local`, etc.
- it makes the program not self-contained and dependent on an external configuration file.

I tried to create a dictionary programatically, with only the few Radius attributes I need, but it's not possible: the radcli header does not expose `rc_handle->dictionary_attributes`.

Is there a better solution than looking for a dictionary at all plausible places?

**Comment by nmav** [comment]
What if there is system default location (different per distribution), and which will be queried when the dictionary field is not available in the config?

**Comment by zorun** [comment]
@nmav that would be nice!  The system default location would be determined by the autotools?

Note that I don't use a config file for radcli, but rather use `rc_add_config` to set the parameters I need.  So the dictionary is currently loaded as:

```
rc_add_config(rh, "dictionary", "/etc/radcli/dictionary", NULL, 0);
```

But the solution should also work in this case (maybe add a global variable in radcli with the path to the "system default location" for the dictionary)

**Comment by nmav** [comment]
Would you like to make a pull request for that?

**Comment by nmav** [comment]
> The system default location would be determined by the autotools?

I guess that's the most reasonable.

> But the solution should also work in this case (maybe add a global variable in radcli with the path to the "system default location" for the dictionary)

We can have a macro to be used in that case (the macro could also be NULL), and if dictionary is seen with a NULL parameter, the compiled-in option is used.

**Comment by mwarning** [comment]
@zorun I also use rc_add_config and would like to provide a dictionary without a file.
Is there any progress so far?

**Comment by mwarning** [comment]
Here is a simple proposal: https://github.com/mwarning/radcli/commit/0c7aefbbf1d679790e8f72b76d1c884b408992ce (it exposes a  rc_read_dictionary_line() method)

**Comment by nmav** [comment]
Why read line-by-line? Isn't it easier to load a dictionary from a full buffer? The advantage of a full buffer is that you can use fmemopen() and share the majority of code with rc_read_dictionary.

**Comment by nmav** [comment]
btw. why not the system-wide approach?

**Comment by mwarning** [comment]
@nmav I did not know fmemopen until now. This might be a better solution of course.

**Comment by mwarning** [comment]
@nmav a related problem I ran into:

When not using rc_read_config(), then rc_read_dictionary() and rc_test_config() need to be called manually. (rc_test_config() calls the internal apply_config() that does important data initialization).

Imho, apply_config() should call rc_test_config(), not the other way around. I gave it a try to change it, but this is totally untested and changes the API..: https://github.com/mwarning/radcli/commit/1053f947981bae7c031b749223a9c18487e277f2

**Comment by aravindprasads** [comment]
Hi @nmav  

Is there any conclusion made on the design to address this requirement? 

Which is better approach:
1) System default location (different per distribution), and which will be queried when the dictionary field is not available in the config?
or
2) A new API to read the dictionary parameters similar to rc_add_config().

**Comment by nmav** [comment]
Hi,
 I think having a new API which will load a dictionary from a buffer better suits the existing API.

**Comment by mwarning** [comment]
@nmav that would be nice. I hope subsequent calls can be used to extend the dictionary.
(I think that is why I proposed a dictionary input by line...)

**Comment by aravindprasads** [comment]
Hi @nmav @mwarning 
Thanks for the suggestions. Will work on it and get back.

**Comment by aravindprasads** [comment]
Hi @nmav @mwarning ,

Made code changes to fix this issue.

Kindly review and let me know your views. Thanks for the suggestions and support.

**Comment by aravindprasads** [comment]
Hi @nmav @mwarning 

Kindly review and let me know your views.

**Comment by aravindprasads** [comment]
Hi @nmav 

Thanks for merging the changes - https://github.com/radcli/radcli/pull/41 

Can we close this issue.
