### ISSUE TITLE
No Namespace support in Radcli

### ISSUE THREAD

**Issue by aravindprasads** [radcli/radcli#30]
In actual deployments, Connectivity to RADIUS Server could be configured through different namespace. This is possible in deployments requiring Management-VRF support in Networks Switches/Routers (VRFs could be implemented with Namespaces). 

Without it, User will be forced to spawn the Radcli process in different Namespace to transmit/receive messages in that Namespace (Which may not be desired if user expects all processes to be placed in same Namespace).

**Comment by nmav** [comment]
Seems reasonable to me. If Martin doesn't do first, I'll try to review your patch.

**Comment by nmav** [comment]
Closed by #29
