### ISSUE TITLE
reject-tests.sh tests fail on travis

### ISSUE THREAD

**Issue by nmav** [radcli/radcli#36]
It seems that there was a bug in CI (see #34 ) and it didn't detect that `reject-tests.sh` fail.   It was introduced at ce075de8759ac60db4e8eafe05b3d648ec6b5bc8.

**Comment by nmav** [comment]
Hi @aravindprasad90 could you take a look?

**Comment by aravindprasads** [comment]
Hi @nmav ,

Yes, looking into this issue now.

**Comment by aravindprasads** [comment]
Hi @nmav ,

Raised https://github.com/radcli/radcli/pull/37 to fix the issue. Kindly review the same.

**Comment by nmav** [comment]
Closed by #37
