### ISSUE TITLE
'radius-acct' not found in FreeBSD 10.1-RELEASE /etc/services

### ISSUE THREAD

**Issue by MattDunwoodie** [radcli/radcli#4]
The service 'radius-acct' as hardcoded in ip_util.c:rc_getaddrinfo is not in the default /etc/services file on FreeBSD 10.1-RELEASE. 

The easy fix is to duplicate the 'radacct' entry in /etc/services and change it to 'radius-acct'. Took me a while to find the cause. 

By no means do I expect a fix (Could take it upstream). This is just to help out anyone who has had the same issue with not being able to connect to an accounting server.

**Comment by nmav** [comment]
Thanks for reporting that.
