### ISSUE TITLE
Secret key mismatch

### ISSUE THREAD

**Issue by salar-ziaei** [radcli/radcli#48]
`127.0.0.1 S@lar1377`
this is my servers file and im sure that my nas client has the same ip address and same secret key but this is what i get

> User-Name = "salar"
> (5)   User-Password = "3\351\311J\212\272\225\2165\252F\201\276\324u6"    **_/*i think this means the keys do not match but they do */_**
> (5)   NAS-IPv6-Address = ::ffff:185.120.222.75
> (5)   Calling-Station-Id = "::ffff:5.121.110.27"
> (5)   Connect-Info = "OpenConnect VPN Agent (Java) v7.04-unknown"
> (5)   Service-Type = Authenticate-Only
> (5)   NAS-Port-Type = Async
> (5)   NAS-Port = 1717
> (5)   NAS-Identifier = "radcli"
> (5) # Executing section authorize from file /etc/freeradius/3.0/sites-enabled/default
>

**Comment by aravindprasads** [comment]
Radius Client functionality looks good as of today. No breakages observed. 

Seems to be misconfig from your side. Kindly verify users, clients.conf file in Radius server side too.

**Comment by salar-ziaei** [comment]
**Radcli servers file**

>  Server Name or Client/Server pair		Key		
> ## ----------------				---------------
> #
> #portmaster.elemental.net			hardlyasecret
> #portmaster2.elemental.net			donttellanyone
> #
> #uncomment the following line for simple testing of radlogin
> #with freeradius-server
> 
> #localhost/localhost				testing123
> localhost				samepassword
> 
-----------------------------------------------------------------------------------------------
**my nas client settings on mysql:**
> Nas ip/host: localhost
> Nas secret: samepassword
> Nas type: other
> Nas shortname: ocserv

**freeradius is working with my router**
**OS: ubuntu 18.04**
