### ISSUE TITLE
ipv4addr clarification

### ISSUE THREAD

**Issue by dpocock** [radcli/radcli#5]
When I made a diff between `/etc/radiusclient` and `/etc/radcli` I noticed that the `dictionary*` files now use `ipv4addr` instead of `ipaddr`

Is `ipaddr` still supported or do people have to modify any existing dictionary files?

Will `ipaddr` go away in future?

Could you please consider creating a document about migration from FreeRADIUS-client with a brief summary about issues like this?

**Comment by nmav** [comment]
> When I made a diff between /etc/radiusclient and /etc/radcli I noticed that the dictionary\* files now 
> use ipv4addr instead of ipaddr
> Is ipaddr still supported or do people have to modify any existing dictionary files?

Yes. Ipv4addr is simply an alias to match ipv6addr.

> Will ipaddr go away in future?

No

> Could you please consider creating a document about migration from FreeRADIUS-client with 
> a brief summary about issues like this?

It is not needed (yet at least). As it is now radcli is backwards compatible with freeradius-client.
