### ISSUE TITLE
freeradius-client compat:  no

### ISSUE THREAD

**Issue by k0tkin** [radcli/radcli#5]
Hi,

After running ./configure --prefix=/usr --sysconfdir=/etc I see freeradius-client compat:  no

First I installed ocserv
And after that I installed libfreeradius-client2 and libfreeradius-client-dev
Did i missed something?

**Comment by nmav** [comment]
The freeradius-client compatibility library is needed if you want radcli to simulate the freeradius-client library. As far as I understand you need radcli for ocserv, so you don't need either the compat library nor the libfreeradius-client library.
