### ISSUE TITLE
rc_auth and rc_acct apis clientPort parameter doesn't work as expected

### ISSUE THREAD

**Issue by rajdippatel-emc** [radcli/radcli#62]
Hello Guys,

I have following usage.

```
VALUE_PAIR *sendValuePair = prepareRequest();
VALUE_PAIR *receivedValuePair = nullptr;
auto result = rc_auth(rcHandle, 1812, sendValuePair, &receivedValuePair, nullptr);

```

When I see source port in wireshark I noticed clientPort is not set properly in UDP source packet. Same thing happens for rc_acct API. From documentation it seems it should work. Do you think I am making any mistake here?

Thanks.

**Comment by nmav** [comment]
I have completely missed this. For the record this is not a UDP port. This is the NAS port number.
