### ISSUE TITLE
Missing namespacing for radcli.h / clashes with MAX()/MIN() etc.

### ISSUE THREAD

**Issue by T-X** [radcli/radcli#78]
As an example, the macro names MAX() and MIN() are very common ones. When trying to use and include radcli.h in opennds you will get the following warnings:

```In file included from src/fw_iptables.c:49:0:
src/util.h:29:0: warning: "MIN" redefined
 #define MIN(X, Y) (((X) < (Y)) ? (X) : (Y))

In file included from src/conf.h:33:0,
                 from src/fw_iptables.c:44:
/openwrt/staging_dir/target-x86_64_musl/usr/include/radcli/radcli.h:498:0: note: this is the location of the previous definition
 #define MIN(a, b)     ((a) < (b) ? (a) : (b))
```

Other macros like BUFFER_LEN or SERVER_MAX seem like they could likely clash, too.

Either prefix all these macros with "RC_". Or somehow refactor them out of the radcli.h, into a libradcli-private header file?

**Comment by nmav** [comment]
Would you like to propose a fix with a PR? I agree we don't need these macros there.

**Comment by aravindprasads** [comment]
Hi @T-X  @nmav 

Made a PR (https://github.com/radcli/radcli/pull/79) with fixes. Kindly let me know if any further changes are needed.
