### ISSUE TITLE
How to debug radcli?

### ISSUE THREAD

**Issue by k0tkin** [radcli/radcli#8]
Hi,

I'm using radcli with my radius server but it seems radcli only authenticate my username and password and after that nothing, I need to see traffic usage of my clients and more important than that seeing when client goes offline

Thank you

**Comment by nmav** [comment]
Hi, to see the radius traffic usage, you have to send radius accounting messages to the server. For an example you may see ocserv's radius accounting code.
https://gitlab.com/ocserv/ocserv/blob/master/src/acct/radius.c
