### ISSUE TITLE
configure.ac use implicit return type for main in one of its checks, not C99 compliant.

### ISSUE THREAD

**Issue by pjfordham** [radcli/radcli#91]
Found as part of this effort:

https://fedoraproject.org/wiki/Toolchain/PortingToModernC

**Comment by pjfordham** [comment]
diff --git a/configure.ac b/configure.ac
index bb868e7..870919c 100644
--- a/configure.ac
+++ b/configure.ac
@@ -122,7 +122,7 @@ then
 	AC_TRY_RUN([
 	#include <sys/utsname.h>
 
-	main(int argc, char **argv)
+	int main(int argc, char **argv)
 	{
 		struct utsname uts;
 		uts.domainname[0] = '\0';

**Comment by nmav** [comment]
Thank you. Would you like to send a pull request?

**Comment by nmav** [comment]
Never mind, pushed a fix.
