### ISSUE TITLE
Constructing Vendor-Specific AVP with Multiple VSAs and Removing specific AVP

### ISSUE THREAD

**Issue by missing233** [radcli/radcli#96]
I'm currently working on a project that involves the use of the radcli library and try to encapsulate several VSAs within a single Vendor-Specific (26) AVP.

OS: Ubuntu: Ubuntu 22.04.3 LTS
radcli: the latest build

Here is a brief overview of the steps I am following:
Initialize rc_handle.
Use rc_avpair_add to create a Vendor-Specific AVP.
The VSAs are not packed into a single AVP but are split into separate AVPs.
I am unsure if I might be missing a step or if there is a specific method to achieve this in radcli. 

Additionally, I am unsure why the final constructed RADIUS packet always includes the AVP: t=NAS-IPv6-Address(95).

**Expected RADIUS Packet Structure (In Wireshark):**
```
Attribute Value Pairs
    AVP: t=User-Name(1) l=21 val=_[username]_
    AVP: t=CHAP-Password(3) l=19 val=_[password]_
    AVP: t=Vendor-Specific(26) l=49 vnd=_vendor-name_vendorid_
        Type: 26
        Length: 49
        Vendor ID: _vendor-name_vendorid_
        VSA: t=CPE-MAC-Address(1) l=16 val=_[CPE-MAC-Address]_
        VSA: t=CPE-Vendor-Name(2) l=8 val=_[CPE-Vendor-Name]_
        VSA: t=CPE-Product-Name(3) l=6 val=_[CPE-Product-Name]_
        VSA: t=CPE-HW-Revision(4) l=13 val=_[CPE-HW-Revision]_
    AVP: t=CHAP-Challenge(60) l=18 val=_[challenge]_
```

**Actual Constructed RADIUS Packet Structure by radcli:**
```
Attribute Value Pairs
    AVP: t=User-Name(1) l=41 val=_[username]_
    AVP: t=CHAP-Password(3) l=19 val=_[password]_
    AVP: t=Vendor-Specific(26) l=22 vnd=_vendor-name_vendorid_
        Type: 26
        Length: 22
        Vendor ID: _vendor-name_vendorid_
        VSA: t=CPE-MAC-Address(1) l=16 val=_[CPE-MAC-Address]_
    AVP: t=Vendor-Specific(26) l=14 vnd=_vendor-name_vendorid_
        Type: 26
        Length: 14
        Vendor ID: __vendor-name_vendorid_
        VSA: t=CPE-Vendor-Name(2) l=8 val=_[CPE-Vendor-Name]_
    AVP: t=Vendor-Specific(26) l=12 vnd=_vendor-name_vendorid_
        Type: 26
        Length: 12
        Vendor ID: __vendor-name_vendorid_
        VSA: t=CPE-Product-Name(3) l=6 val=_[CPE-Product-Name]_
    AVP: t=Vendor-Specific(26) l=19 vnd=_vendor-name_vendorid_
        Type: 26
        Length: 19
        Vendor ID: __vendor-name_vendorid_
        VSA: t=CPE-HW-Revision(4) l=13 val=_[CPE-HW-Revision]_
    AVP: t=CHAP-Challenge(60) l=18 val=_[challenge]_
    AVP: t=NAS-IPv6-Address(95) l=18 val=_fd15:[unknown-ipv6-address]:48c8_
```
**Here is my code snippet:**
```
rc_handle *rh = rc_new();
... // initial radius dict
VALUE_PAIR *send;
if (rc_avpair_add(rh, &send, PW_USER_NAME, username, strlen(username), VENDOR_NONE) == NULL)
{
    fprintf(stderr, "ERROR: cannot add USERNAME: %s\n", username);
    rc_destroy(rh);
    return ERROR_RC;
} 
...
if (rc_avpair_add(rh, &send, kMacID, mac, strlen(mac), kVendorID) == NULL)
{
      fprintf(stderr, "ERROR: unable to set MAC: %s\n", mac);
      rc_destroy(rh);
      return ERROR_RC;
}
if (rc_avpair_add(rh, &send, kManufacturerID, kManufacturer, strlen(kManufacturer), kVendorID) == NULL)
{
      fprintf(stderr, "ERROR: unable to set manufacturer: %s\n", kManufacturer);
      rc_destroy(rh);
      return ERROR_RC;
 }
... // other VSAs
VALUE_PAIR *received = NULL;
  int result = rc_aaa(rh, 0, send, &received, NULL, 0, PW_ACCESS_REQUEST);
  if (result != OK_RC)
  {
    fprintf(stderr, " RADIUS Authentication failure (RC=%d)\n", result);
    rc_destroy(rh);
    return ERROR_RC;
  }
```
How can I use radcli to send an Expected RADIUS Packet Structure that contains multiple Vendor-Specific Attributes (VSAs)?
Additionally, how can I remove the specific AVP: t=NAS-IPv6-Address(95)?

Any guidance or examples you could provide would be greatly appreciated.

**Comment by nmav** [comment]
From a quick glimpse that looks like a memory corruption there. Try setting send to NULL and if that's not it, try valgrind or asan. If that's not it, please provide more information on why this is an issue on radcli.

**Comment by missing233** [comment]
> From a quick glimpse that looks like a memory corruption there. Try setting send to NULL and if that's not it, try valgrind or asan. If that's not it, please provide more information on why this is an issue on radcli.


Sorry, what I meant was how to pack multiple VSAs into a vendor-specific attribute, similar to the expected RADIUS packet structure
